### ISSUE TITLE
Is there a way to specify an offset like you can in gbm. step? 

### ISSUE THREAD

**Issue by nffarabaugh** [SimonDedman/gbm.auto#76] opened 2022-10-23 20:07 UTC
Hello in gbm.step you can specify  an offset with the "  offset = " command. 
I was wondering if you could do the same or similar was possible with Gbm.auto and if so how might you do it!

**Comment by SimonDedman** [comment] 2022-10-28 08:09
The "..." parameter of gbm.auto allows you to pass any commands you like to gbm.auto and they'll be available in the environment to some of the functions beneath, in this case breaks.grid, legend, and gbm.step (technically gbm.step.sd now). So it should just work. Maybe do a side-by-side comparison within/without to check there's a difference. What does offset do? Dismo's help note says "offset", which isn't helpful!

**Comment by nffarabaugh** [comment] 2022-11-04 00:11
Thanks that is so incredibly obvious. Not sure why it didn't occur to me to start with! I still seem to be throwing and error however. 

My understanding  is that an offset here is similar to an off set in a GLM. (https://towardsdatascience.com/offsetting-the-model-logic-to-implementation-7e333bc25798). In this case I am using an offset to account for a difference in sampling effort (specifically in soak time of cameras) in count/abundance data for marine data.  
I have found that there is a quirk in the offset command in  gbm.step where you have to specify the data frame. So instead of  "offset = name_of_offset_column" you must type "name_of_dataframe$name_of_offset_column". 

This seems not to be an issue in your package. However I do get an error of "Error in ans + x[[i]] : non-numeric argument to binary operator". 

Any thoughts on a solution? Thanks very much!

**Comment by SimonDedman** [comment] 2022-11-04 00:36
update based on chats: error has changed once name_of_dataframe$name_of_offset_column entered without quotes - please quote new error and we can try to diagnose the cause.

gbm.auto uses gbm.step.sd which is the same code with some extra stuff added which shouldn't affect this stuff but clearly it's not working...

**Comment by nffarabaugh** [comment] 2022-11-04 13:08
Error when offset entered as: name_of_dataframe$name_of_offset_column, sans quotes 

Error in model.frame.default(formula = y.subset ~ . + offset(offset.subset),  : 
  variable lengths differ (found for 'offset(offset.subset)')

**Comment by SimonDedman** [comment] 2023-05-18 03:58
fixed in [c4ecdb2](https://github.com/SimonDedman/gbm.auto/commit/c4ecdb2c426153256b19f3506e2c2f87578283cf) & [8ee587f](https://github.com/SimonDedman/gbm.auto/commit/8ee587f0a1f56038b8d692e29d0d6859e102ea66)

**Closed by SimonDedman** 2023-05-18 03:58 UTC
